{
	"version": 1722712693,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg_petualangan-sheet0.png",
		"images/btn_jump-sheet0.png",
		"images/btn_left-sheet0.png",
		"images/btn_nav-sheet0.png",
		"images/btn_right-sheet0.png",
		"images/out-sheet0.png",
		"images/group3-sheet0.png",
		"images/group4-sheet0.png",
		"images/img_7-sheet0.png",
		"images/karakter-sheet0.png",
		"images/karakter-sheet1.png",
		"images/karakter-sheet2.png",
		"images/key-sheet0.png",
		"images/musuh-sheet0.png",
		"images/tanah1.png",
		"images/tanah-sheet0.png",
		"images/nyawa-sheet0.png",
		"images/skor-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tanah4-sheet0.png",
		"images/tanah2-sheet0.png",
		"images/bayangan-sheet0.png",
		"images/benda_gas-sheet0.png",
		"images/benda_gas-sheet1.png",
		"images/keranjang-sheet0.png",
		"images/untitled2-sheet0.png",
		"images/petunjuk_1-sheet0.png",
		"images/layout_home-sheet0.png",
		"images/btn_mute-sheet0.png",
		"images/btn_belajar-sheet0.png",
		"images/btn_bermain-sheet0.png",
		"images/img_6-sheet0.png",
		"images/spritefont.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/benda_cair-sheet0.png",
		"images/benda_padat-sheet0.png",
		"images/benda_padat-sheet1.png",
		"images/benda_padat-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/next_start-sheet0.png",
		"images/next_start2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/next_3-sheet0.png",
		"images/pop_index-sheet0.png",
		"images/pop_index-sheet1.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/test-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/belajar_layout-sheet0.png",
		"images/btn_home-sheet0.png",
		"images/btn_home-sheet1.png",
		"images/btn_forward-sheet0.png",
		"images/btn_forward-sheet1.png",
		"images/btn_retreat-sheet0.png",
		"images/belajar_layout_2-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/mtr_padat-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/frame_mencair-sheet0.png",
		"images/frame_mencair-sheet1.png",
		"images/frame_mencair-sheet2.png",
		"images/frame_menyublim-sheet0.png",
		"images/frame_menyublim-sheet1.png",
		"images/frame_menyublim-sheet2.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/frame_membeku-sheet0.png",
		"images/frame_membeku-sheet1.png",
		"images/frame_membeku-sheet2.png",
		"images/frame_menguap-sheet0.png",
		"images/frame_menguap-sheet1.png",
		"images/frame_menguap-sheet2.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/frame_mengkristal-sheet0.png",
		"images/frame_mengkristal-sheet1.png",
		"images/frame_mengkristal-sheet2.png",
		"images/frame_mengembun-sheet0.png",
		"images/frame_mengembun-sheet1.png",
		"images/frame_mengembun-sheet2.png",
		"images/btn_return-sheet0.png",
		"images/belajar_layout_3-sheet0.png",
		"images/btn_perubahan_cair-sheet0.png",
		"images/btn_perubahan_cair-sheet1.png",
		"images/btn_benda_padat-sheet0.png",
		"images/quiz-sheet0.png",
		"images/quiz-sheet1.png",
		"images/opsi_j-sheet0.png",
		"images/opsi_j-sheet1.png",
		"images/index-sheet0.png",
		"images/index2-sheet0.png",
		"images/index3-sheet0.png",
		"images/index4-sheet0.png",
		"images/icon_respon_kuis-sheet0.png",
		"images/icon_respon_kuis-sheet1.png",
		"images/icon_respon_kuis-sheet2.png",
		"images/tiledbackground.png",
		"images/soal-sheet0.png",
		"images/soal-sheet1.png",
		"images/evaluasi_opsi-sheet0.png",
		"images/evaluasi_opsi-sheet1.png",
		"images/no_soal-sheet0.png",
		"images/no_soal-sheet1.png",
		"images/tanda-sheet0.png",
		"images/tanda-sheet1.png",
		"images/btn_evaluasi_selesai-sheet0.png",
		"images/btn_perubahan_gas-sheet0.png",
		"images/btn_perubahan_gas-sheet1.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/petualangan_finis-sheet0.png",
		"images/boom-sheet0.png",
		"images/boom-sheet1.png",
		"images/jawaban_no_1_5-sheet0.png",
		"images/jawaban_no_1_5-sheet1.png",
		"images/jawaban_no_6-sheet0.png",
		"images/jawaban_no_7-sheet0.png",
		"images/jawaban_no_8-sheet0.png",
		"images/jawaban_no_9-sheet0.png",
		"images/jawaban_no_10-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/btn_false-sheet0.png",
		"images/frame_tema7-sheet0.png",
		"images/bg.png",
		"images/tanahtinggi.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/hiasan-sheet0.png",
		"images/hiasan-sheet1.png",
		"images/tiledbackground4.png",
		"images/sprite8-sheet0.png",
		"images/btn_play-sheet0.png",
		"images/btn_pause-sheet0.png",
		"images/bg_papan-sheet0.png",
		"images/bg_video-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/pop_up_video-sheet0.png",
		"images/frame_petunjuk-sheet0.png",
		"images/frame_petunjuk-sheet1.png",
		"images/frame_opening-sheet0.png",
		"images/btn_mulai-sheet0.png",
		"images/btn_petunjuk-sheet0.png",
		"images/btn_tandaseru-sheet0.png",
		"media/jenis benda.ogg",
		"media/pembukaan (enhanced)-[audiotrimmer.com].ogg",
		"media/pengertian wujud benda (enhanced)-[audiotrimmer.com].ogg",
		"media/benda cair.ogg",
		"media/benda gas cut.ogg",
		"media/benda padat cut.ogg",
		"media/membeku cut.ogg",
		"media/mencair cut.ogg",
		"media/mengembun cut.ogg",
		"media/mengkristal cut.ogg",
		"media/menguap cut.ogg",
		"media/menyublim cut.ogg",
		"media/sifat benda cair cut.ogg",
		"media/sifat benda padat cut.ogg",
		"media/sifat gas cut.ogg",
		"media/bahan membeku cut.ogg",
		"media/bahan mencair.ogg",
		"media/bahan mengembun cut.ogg",
		"media/bahan menguap cut.ogg",
		"media/cara kerja membeku cut.ogg",
		"media/cara kerja mencair.ogg",
		"media/cara kerja mengembun cut.ogg",
		"media/cara kerja menguap cut.ogg",
		"media/mengkristal bahan cut revisi.ogg",
		"media/mengkristal percobaan cut revisi.ogg",
		"media/menyublim bahan cut revisi.ogg",
		"media/menyublim percobaan cut revisi.ogg",
		"media/cur_mencair.ogg",
		"media/cut_gas.ogg",
		"media/cut_mengkristal.ogg",
		"media/demage.ogg",
		"media/hit.ogg",
		"media/jump.ogg",
		"media/level_selesai.ogg",
		"media/notifikasi.ogg",
		"media/push_button.ogg",
		"media/quiz.ogg",
		"media/completed.ogg",
		"media/explosion.ogg",
		"media/tepuk-tangan.ogg",
		"media/uwaw.ogg",
		"media/benar.ogg",
		"media/nice.ogg",
		"media/salah.ogg",
		"media/base.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}